### ISSUE TITLE
Switch to on-demand when capacity unavailable

### ISSUE THREAD

**Issue by chruzie** [keikoproj/minion-manager#13]
Good Afternoon,

I was just wondering if it was possible to add a feature to switch to on-demand instances when capacity is unavailable and the request could not be be fulfilled?

**Comment by shrinandj** [comment]
AWS is moving towards using [LaunchTemplates](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-launch-templates.html) instead of LaunchConfigurations. LaunchTemplates allow specifying multiple instance types and thereby reducing the chances running out of capacity one anyone of them.

Suggestions welcome; PRs more than welcome ;-)

**Comment by alantang888** [comment]
But if using k8s-minion-manager with autoscaler will need this feature. Because autoscaler don't want to support multiple instance types. To [prevent wrong calculate resource](github.com/kubernetes/autoscaler/pull/1473).

**Comment by tekenstam** [comment]
Will not do. This project is end-of-life and is no longer maintained/supported.
